#!/bin/bash

. $csc/scripts/cs-common

function print_usage() {
  echo "Usage: s-merge -l <left-graph> -r <right-graph> -o <output-file> "
  echo "               [ -m <request-count> ] [ -y <left-is-full-merge> ]"
  echo "               [ -c <watch,list,codes> ]"
  echo "               [ -w <watch-file> ]"
  echo "                  watch file entries:"
  echo "                      0x12345678|0x14 # node and all edges"
  echo "                      0x12345678      # all nodes in a routine"
  exit
}

check_help $1 print_usage

append_classpath "SCRIPT_SAFE_MERGE_DIR"
append_classpath "CROWD_SAFE_COMMON_DIR"

# echo "classpath: $cp"

main_class="edu.uci.plrg.cfi.php.merge.main.ScriptSafeMerge"

java $vm_args -cp $cp $main_class $@

