#!/bin/bash

. $csc/scripts/cs-common

function usage() {
  echo "ulc -d <dataset-dir> -s <php-src-dir>"
}

check_help $1 usage

append_classpath "CROWD_SAFE_COMMON_DIR"
append_classpath "SCRIPT_SAFE_MERGE_DIR"

main_class="edu.uci.plrg.cfi.php.analysis.dictionary.UserLevelCoverage"

#echo "java -cp $cp $main_class $@"
java -Xms512M -Xmx2048M -cp $cp $main_class $@
