#!/bin/bash

function usage() {
  echo "w-merge -o <output-dir> <run-dir> [ <run-dir> ... ]"
}

[ "$1" == "--help" ] && usage && exit

while getopts "o:v:" option
do
  case $option in
    o) output_dir=$OPTARG;;
    v) verbose="-v $OPTARG";;
  esac
done
shift $(( $OPTIND - 1 ))

[ -z "$output_dir" ] && usage && exit

if [ ! -f $output_dir/cfg.set ]
then # starting a new dataset
  for d in "${@}"
  do
    shift # N.B.: first run is the base!
    [ -s $d/request.tab ] && right=$d && break
  done

  for d in "${@}"
  do
    shift
    [ -s $d/request.tab ] && left=$d && break
  done

  [ -z "$left" ] && left=$right
  [ -z "$right" ] && echo "Failed to find a non-empty run. Exiting with nothing to do." && exit

  echo "Merging $# workers into a new dataset"
  s-merge $verbose -o $output_dir -l $left -r $right 
  [ $? -ne 0 ] && echo "Error, exiting now." && exit
  shift 2
else
  echo "Merge $# workers into dataset $output_dir/cfg.set"
  rm -f $output_dir/merge.log
fi

for d in "${@}"
do
  [ -s $d/request.tab ] || { echo "Skipping empty directory $d" && continue; }
  s-merge $verbose -o $output_dir -l $d
  [ $? -ne 0 ] && echo "Error, exiting now." && exit
done

