#!/bin/bash

function usage() {
  echo "w-merge -o <output-dir> <run-dir> [ <run-dir> ... ]"
}

[ "$1" == "--help" ] && usage && exit

while getopts "o:" option
do
  case $option in
    o) output_dir=$OPTARG;;
  esac
done
shift $(( $OPTIND - 1 ))

[ -z "$output_dir" ] && usage && exit

if [ ! -f $output_dir/cfg.set ]
then # starting a new dataset
  echo "Merging $# workers into a new dataset"
  s-merge -o $output_dir -l $2 -r $1 # N.B.: first run is the base!
  [ $? -ne 0 ] && echo "Error, exiting now." && exit
  shift 2
else
  echo "Merge $# workers into dataset $output_dir/cfg.set"
  rm -f $output_dir/merge.log
fi

for d in "${@}"
do
  [ -s $d/request.tab ] || { echo "Skipping empty directory $d" && continue; }
  s-merge -o $output_dir -l $d
  [ $? -ne 0 ] && echo "Error, exiting now." && exit
done

